# 声明式对象配置：通过apply命令和配置文件去操作kubernetes的资源
# kubectl apply -f nginx-pod.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  namespace: dev
spec:
  containers:
    - name: nginx-containers
      image: nginx:1.17.1